version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: training-3
    expose:
      - '3030'
    ports:
      - '3030:3030'
    command: npm run dev
    env_file:
      - .env
