version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: app
    expose:
      - '3030'
    ports:
      - '3030:3030'
    command: npm run dev
    env_file:
      - .env

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1tc2020

  mongo-express:
    container_name: mongo_admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1tc2020
      ME_CONFIG_MONGODB_URL: mongodb://admin:1tc2020@mongo:27017/

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'